config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root to: "questions#index"

  concern :votable do
    patch :rate, on: :member
    delete :unrate, on: :member
  end

  get '/auth_confirmations', to: 'auth_confirmations#finish'
  get '/auth_confirmations/new', to: 'auth_confirmations#new'
  post '/auth_confirmations', to: 'auth_confirmations#create'

  resources :questions do
    resources :comments, shallow: true
    resources :answers, shallow: true do
      resources :comments, shallow: true
      post :best, on: :member
      concerns :votable
    end
    concerns :votable
    resources :subscribtions, only: [:create, :destroy], shallow: true
  end


  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end
      resources :questions, on: :member do
        resources :answers, shallow: true
      end
    end
  end

  resources :attachments, only: [:destroy]

  resources :search, only: :index

  mount ActionCable.server => '/cable'
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :attachable, polymorphic: true, optional: true
  mount_uploader :file, FileUploader
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_attachment, only: [:destroy]

  authorize_resource

  def destroy
    respond_with(@attachment.destroy)
  end

  private

  def load_attachment
    @attachment = Attachment.find(params[:id])
  end
end

app/views/attachments/_attachment.html.slim
div class="attachment attachment-#{attachment.id}"  
  = link_to attachment.file.filename, attachment.file.url
  - if can?(:destroy, attachment)
    = link_to 'Delete file', attachment_path(attachment), method: :delete, data: { confirm: "Are you sure?" }, remote: true

app/views/attachments/destroy.js.erb
$('.notice').html('<%= notice %>')
$('.alert').html('<%= alert %>')

$('.attachment-<%= @attachment.id %>').remove();