config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root to: "questions#index"

  concern :votable do
    patch :rate, on: :member
    delete :unrate, on: :member
  end

  get '/auth_confirmations', to: 'auth_confirmations#finish'
  get '/auth_confirmations/new', to: 'auth_confirmations#new'
  post '/auth_confirmations', to: 'auth_confirmations#create'

  resources :questions do
    resources :comments, shallow: true
    resources :answers, shallow: true do
      resources :comments, shallow: true
      post :best, on: :member
      concerns :votable
    end
    concerns :votable
    resources :subscribtions, only: [:create, :destroy], shallow: true
  end


  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end
      resources :questions, on: :member do
        resources :answers, shallow: true
      end
    end
  end

  resources :attachments, only: [:destroy]

  resources :search, only: :index

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable
  include Attachable

  belongs_to :question, touch: true
  belongs_to :user

  validates :body, :question_id, :user_id, presence: true

  accepts_nested_attributes_for :attachments, reject_if: :all_blank
  after_create :notify_question_author

  def best!
    ActiveRecord::Base.transaction do
      best_answer = question.answers.find_by(best: true)
      if best_answer.present?
        best_answer.update!(best: false)
      end
      update!(best: true)
    end
  end

  private

  def notify_question_author
    QuestionSubscriberJob.perform_later(self.question)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!
  before_action :find_question, only: [:create]
  before_action :load_answer, only: [:update, :destroy, :best]
  after_action :publish_answer, only: [:create]

  authorize_resource

  def create
    respond_with(@answer = @question.answers.create(answer_params.merge(user: current_user)))
  end

  def update
    @answer.update(answer_params)
    respond_with(@answer)
  end

  def destroy
    respond_with(@answer.destroy)
  end

  def best
    @question = @answer.question
    respond_with(@answer.best!)
  end

  private

  def publish_answer
    return if @answer.errors.any?
    ActionCable.server.broadcast(
      "answers_for_#{@question.id}",
      { answer: @answer.attributes.merge(attachments: @answer.attachments) }
    )
  end

  def load_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:id, :file, :_destroy])
  end

  def find_question
    @question = Question.find(params[:question_id])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :find_question, only: [:create]

  authorize_resource

  def show
    @answer = Answer.find(params[:id])
    respond_with @answer
  end

  def index
    @answers = Answer.where(question_id: params[:question_id])
    respond_with @answers, each_serializer: AnswersSerializer
  end

  def create
    respond_with(@answer = @question.answers.create(answer_params.merge(user: current_resource_owner)))
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def find_question
    @question = Question.find(params[:question_id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- cache [user_signed_in?, answer] do
  .answer class="answer-#{ answer.id }#{answer.best ? ' best-answer' : ''}"
    .answer-body = answer.body
    = render 'shared/rating', votable: answer

    p Attachments:
    div
      - answer.attachments.each do |attachment|
        = render attachment

    - if can?(:best, answer) && !answer.best
        p= link_to 'Best', best_answer_path(answer), method: :post, remote: true

    -if can?(:destroy, answer)
      p= link_to 'Delete', answer, method: :delete, data: { confirm: "Are you sure?" }, remote: true

    -if can?(:update, answer)
      p= link_to 'Edit', '', class: 'edit-answer-link', data: { answer_id: answer.id }
      p
        = form_for answer, remote: true, html: { id: "edit-answer-#{answer.id}" } do |f|
          p= f.label :body, 'Answer'
          p= f.text_area :body
          p= f.submit 'Save'

    div class="comments comments-#{answer.id}"
      - if can?(:create, Comment)
        = render 'comments/form', commentable: answer
      - if answer.comments.any?
        = render answer.comments

app/views/answers/_form_errors.html.slim
= errors.full_messages.to_sentence

app/views/answers/best.js.erb
$('.form-errors').html('');
$('.notice').html("<%= notice %>");
$('.alert').html("<%= alert %>");

<% if @answer.errors.present? %>
  $('.form-errors').html("<%= j render 'form_errors', errors: @answer.errors %>");
<% else %>
  $('.answers').html("<%= j render @question.answers %>");
<% end %>

app/views/answers/create.js.erb
$('#answer_body').val("");
$('.form-errors').html("");
$('.notice').html("<%= notice %>");

<% if @answer.errors.any? %>
  $('.form-errors').html("<%= j render 'form_errors', errors: @answer.errors %>");
<% end %>

app/views/answers/destroy.js.erb
$('.notice').html("<%= notice %>");
$('.alert').html("<%= alert %>");

$('<%= ".answer-#{ @answer.id }" %>').remove(); 

app/views/answers/update.js.erb
$('.form-errors').html("");
$('.notice').html("<%= notice %>");
$('.alert').html("<%= alert %>");

<% if @answer.errors.any? %>
  $('.form-errors').html("<%= j render 'form_errors', errors: @answer.errors %>");
<% else %>
  $('<%= ".answer-#{@answer.id}" %>').replaceWith("<%= j render @answer %>");    
<% end %>