config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root to: "questions#index"

  concern :votable do
    patch :rate, on: :member
    delete :unrate, on: :member
  end

  get '/auth_confirmations', to: 'auth_confirmations#finish'
  get '/auth_confirmations/new', to: 'auth_confirmations#new'
  post '/auth_confirmations', to: 'auth_confirmations#create'

  resources :questions do
    resources :comments, shallow: true
    resources :answers, shallow: true do
      resources :comments, shallow: true
      post :best, on: :member
      concerns :votable
    end
    concerns :votable
    resources :subscribtions, only: [:create, :destroy], shallow: true
  end


  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end
      resources :questions, on: :member do
        resources :answers, shallow: true
      end
    end
  end

  resources :attachments, only: [:destroy]

  resources :search, only: :index

  mount ActionCable.server => '/cable'
end

app/models/subscribtion.rb
class Subscribtion < ApplicationRecord
  belongs_to :user
  belongs_to :subscribable, polymorphic: true
  validates :user, presence: true, uniqueness: { scope: :subscribable_id }
end

app/controllers/subscribtions_controller.rb
class SubscribtionsController < ApplicationController
  before_action :load_question, only: [:create]
  before_action :find_subscribtion, only: [:destroy]
  respond_to :js

  authorize_resource

  def create
    respond_with(@subscribtion = current_user.subscribe(@question))
  end

  def destroy
    respond_with(@subscribtion.destroy)
  end

  private

  def find_subscribtion
    @subscribtion = Subscribtion.find(params[:id])
  end

  def load_question
    @question = Question.find(params[:question_id])
  end
end

app/helpers/subscribtions_helper.rb
module SubscribtionsHelper
end

app/views/subscribtions/_subscribtion.html.slim
- if can?(:create, Subscribtion) && can?(:destroy, Subscribtion)
  .subscribtion-block
    - subscription = current_user.subscribtion_for(question)
    - unless subscription.present?
      = link_to 'Subscribe', question_subscribtions_path(question),
        method: :post,
        remote: true,
        class: 'subscribe-button'
    - else
      = link_to 'Unsubscribe', subscribtion_path(subscription),
        method: :delete,
        remote: true,
        class: 'unsubscribe-button'

app/views/subscribtions/create.js.erb
$('.alert, .notice').text('')
$('.notice').html("<%= notice %>");

<% if @subscribtion.errors.any? %>
  $('.alert').html("<%= j @subscribtions.errors.full_messages.to_sentence %>");
<% else %>
  $('.subscribtion-block').html('<%= render "subscribtions/subscribtion", question: @question %>')
<% end %>

app/views/subscribtions/destroy.js.erb
$('.alert, .notice').text('')
$('.notice').html("<%= notice %>");
$('.subscribtion-block').html('<%= render "subscribtions/subscribtion", question: @subscribtion.subscribable %>')