config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root to: "questions#index"

  concern :votable do
    patch :rate, on: :member
    delete :unrate, on: :member
  end

  get '/auth_confirmations', to: 'auth_confirmations#finish'
  get '/auth_confirmations/new', to: 'auth_confirmations#new'
  post '/auth_confirmations', to: 'auth_confirmations#create'

  resources :questions do
    resources :comments, shallow: true
    resources :answers, shallow: true do
      resources :comments, shallow: true
      post :best, on: :member
      concerns :votable
    end
    concerns :votable
    resources :subscribtions, only: [:create, :destroy], shallow: true
  end


  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end
      resources :questions, on: :member do
        resources :answers, shallow: true
      end
    end
  end

  resources :attachments, only: [:destroy]

  resources :search, only: :index

  mount ActionCable.server => '/cable'
end

app/views/layouts/_menu.html.slim
nav [class="navbar navbar-default"]
  div.container-fluid
    a< href="#{questions_path}" Questions 
    - if can?(:create, Question)
      a< href="#{new_question_path}" 
        | Ask question       
    - unless current_user
        a< href="#{ user_session_path }"
          | Sign in
        a< href="#{ new_user_registration_path }"
          | Sign up
    - else
        = link_to "Sign out", destroy_user_session_path, :method => :delete

app/views/layouts/application.html.slim
doctype html
html
  head
    title My App
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = include_gon
    = stylesheet_link_tag    "application", media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = csrf_meta_tags
    = action_cable_meta_tag

  body
    .container-fluid
      = render partial: 'layouts/menu'    
      p.notice= notice
      p.alert= alert
      = yield